server:
  port: 9222

spring:
  application:
    name: VR-CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/tsitotaw/vr-config-server
          clone-on-start: true


